export const materialTypes = ["Notes", "Assignment", "Practice Sheet", "Other Material"];

export const exams = [
  "IOQM",
  "RMO",
  "NMTC",
  "SEHSS",
  "CBSE Class IX",
  "CBSE Class X",
];

export const topics = ["Number Theory", "Algebra", "Geometry", "Combinatorics"];

export const studyMaterials = [
  {
    id: "ioqm-geometry-practice-1",
    title: "Geometry Practice Sheet 1",
    exam: "IOQM",
    topic: "Geometry",
    type: "Practice Sheet",
    description: "Focused geometry problems covering triangles, angles, and construction ideas.",
    label: "PDF Resource",
    updated: "10 Jun 2026",
  },
  {
    id: "ioqm-number-theory-notes",
    title: "Number Theory Complete Notes",
    exam: "IOQM",
    topic: "Number Theory",
    type: "Notes",
    description: "Structured notes for divisibility, primes, congruences, and modular arithmetic.",
    label: "PDF Notes",
    updated: "08 Jun 2026",
  },
  {
    id: "rmo-algebra-assignment",
    title: "Algebra Assignment Set A",
    exam: "RMO",
    topic: "Algebra",
    type: "Assignment",
    description: "Olympiad-style algebra questions on equations, inequalities, and polynomials.",
    label: "PDF Assignment",
    updated: "06 Jun 2026",
  },
  {
    id: "rmo-geometry-notes",
    title: "Geometry Lemmas and Theorems",
    exam: "RMO",
    topic: "Geometry",
    type: "Notes",
    description: "A concise theory pack for angle chasing, cyclic quadrilaterals, and triangles.",
    label: "PDF Notes",
    updated: "05 Jun 2026",
  },
  {
    id: "nmtc-combinatorics-practice",
    title: "Counting Principles Practice",
    exam: "NMTC",
    topic: "Combinatorics",
    type: "Practice Sheet",
    description: "Practice cases, arrangements, combinations, and basic counting strategies.",
    label: "PDF Resource",
    updated: "03 Jun 2026",
  },
  {
    id: "sehss-algebra-other",
    title: "Polynomial Identities Reference",
    exam: "SEHSS",
    topic: "Algebra",
    type: "Other Material",
    description: "Reference sheet for common identities, factorization forms, and examples.",
    label: "Reference PDF",
    updated: "01 Jun 2026",
  },
  {
    id: "cbse-ix-geometry-assignment",
    title: "Circles Assignment",
    exam: "CBSE Class IX",
    topic: "Geometry",
    type: "Assignment",
    description: "School-level assignment on chords, arcs, and angle properties in circles.",
    label: "PDF Assignment",
    updated: "30 May 2026",
  },
  {
    id: "cbse-x-algebra-practice",
    title: "Linear Equations Practice Sheet",
    exam: "CBSE Class X",
    topic: "Algebra",
    type: "Practice Sheet",
    description: "Practice sheet for pair of linear equations and word-problem modelling.",
    label: "PDF Resource",
    updated: "28 May 2026",
  },
  {
    id: "nmtc-number-theory-other",
    title: "Divisibility Tricks Quick Reference",
    exam: "NMTC",
    topic: "Number Theory",
    type: "Other Material",
    description: "Quick reference for common divisibility tests and useful contest shortcuts.",
    label: "Reference PDF",
    updated: "25 May 2026",
  },
];
