export const lectures = [
  {
    id: "ioqm-number-theory-1",
    lectureNumber: 1,
    title: "Divisibility Rules",
    exam: "IOQM",
    topic: "Number Theory",
    duration: "Live since 06:00 PM",
    status: "Live",
    chapter: "Basics and real life applications",
    action: "Join Live",
    link: "#",
  },
  {
    id: "ioqm-algebra-2",
    lectureNumber: 2,
    title: "Quadratic Equations",
    exam: "IOQM",
    topic: "Algebra",
    duration: "Today, 08:00 PM",
    status: "Upcoming",
    chapter: "Roots, graphs and Olympiad patterns",
    action: "View Details",
    link: "#",
  },
  {
    id: "rmo-geometry-3",
    lectureNumber: 3,
    title: "Triangles",
    exam: "RMO",
    topic: "Geometry",
    duration: "48 min",
    status: "Recorded",
    chapter: "Similarity, angle chasing and proofs",
    action: "Watch Lecture",
    link: "#",
  },
  {
    id: "rmo-number-theory-4",
    lectureNumber: 4,
    title: "Modular Arithmetic",
    exam: "RMO",
    topic: "Number Theory",
    duration: "55 min",
    status: "Recorded",
    chapter: "Remainders, residues and congruences",
    action: "Watch Lecture",
    link: "#",
  },
  {
    id: "nmtc-combinatorics-5",
    lectureNumber: 5,
    title: "Counting Principles",
    exam: "NMTC",
    topic: "Combinatorics",
    duration: "42 min",
    status: "Recorded",
    chapter: "Addition, multiplication and cases",
    action: "Watch Lecture",
    link: "#",
  },
  {
    id: "sehss-algebra-6",
    lectureNumber: 6,
    title: "Polynomials",
    exam: "SEHSS",
    topic: "Algebra",
    duration: "Tomorrow, 07:30 PM",
    status: "Upcoming",
    chapter: "Factor theorem and identities",
    action: "View Details",
    link: "#",
  },
  {
    id: "cbse-geometry-7",
    lectureNumber: 7,
    title: "Circles",
    exam: "CBSE IX & X",
    topic: "Geometry",
    duration: "38 min",
    status: "Recorded",
    chapter: "Tangents, chords and angle properties",
    action: "Watch Lecture",
    link: "#",
  },
  {
    id: "cbse-algebra-8",
    lectureNumber: 8,
    title: "Linear Equations",
    exam: "CBSE IX & X",
    topic: "Algebra",
    duration: "35 min",
    status: "Recorded",
    chapter: "Pair of equations and applications",
    action: "Watch Lecture",
    link: "#",
  },
];

export const exams = ["IOQM", "RMO", "NMTC", "SEHSS", "CBSE IX & X"];

export const topics = ["Number Theory", "Algebra", "Geometry", "Combinatorics"];
