export const manageMockTestsExams = [
  "IOQM",
  "RMO",
  "NMTC",
  "SEHSS",
  "CBSE Class IX",
  "CBSE Class X",
];

export const manageMockTestsTopics = [
  "Number Theory",
  "Algebra",
  "Geometry",
  "Combinatorics",
  "Full Syllabus",
];

export const manageMockTestTypes = [
  "Free Mock",
  "Topic Test",
  "Full Test Series",
  "Live Mock",
  "Diagnostic",
];

export const manageMockTestPlatforms = [
  "Google Forms",
  "Quizizz",
  "Microsoft Forms",
  "Typeform",
  "External LMS",
];

export const manageMockTestStatuses = [
  "Draft",
  "Live",
  "Upcoming",
  "Completed",
];

export const manageMockTestsInitialForm = {
  title: "",
  exam: manageMockTestsExams[0],
  topic: manageMockTestsTopics[0],
  testType: manageMockTestTypes[0],
  accessType: "Free",
  externalUrl: "",
  platform: manageMockTestPlatforms[0],
  duration: "",
  questions: "",
  marks: "",
  date: "",
  status: "Draft",
};

export const manageMockTestsSeedTests = [
  {
    id: 1,
    title: "IOQM Live Mock Test - 01",
    exam: "IOQM",
    topic: "Number Theory",
    testType: "Live Mock",
    accessType: "Pro",
    externalUrl: "https://forms.google.com/mbc-ioqm-live-01",
    platform: "Google Forms",
    duration: "3 hours",
    questions: 30,
    marks: 100,
    date: "2026-06-18",
    status: "Live",
  },
  {
    id: 2,
    title: "Foundation Free Mock Test",
    exam: "CBSE Class IX",
    topic: "Algebra",
    testType: "Free Mock",
    accessType: "Free",
    externalUrl: "https://quizizz.com/mbc-foundation-free",
    platform: "Quizizz",
    duration: "60 min",
    questions: 30,
    marks: 60,
    date: "2026-06-15",
    status: "Live",
  },
  {
    id: 3,
    title: "SEHSS Practice Test - Algebra",
    exam: "SEHSS",
    topic: "Algebra",
    testType: "Topic Test",
    accessType: "Pro",
    externalUrl: "https://forms.google.com/mbc-sehss-algebra",
    platform: "Google Forms",
    duration: "75 min",
    questions: 45,
    marks: 90,
    date: "2026-06-22",
    status: "Upcoming",
  },
  {
    id: 4,
    title: "RMO Geometry Angle Chase",
    exam: "RMO",
    topic: "Geometry",
    testType: "Topic Test",
    accessType: "Pro",
    externalUrl: "https://forms.office.com/mbc-rmo-geometry",
    platform: "Microsoft Forms",
    duration: "90 min",
    questions: 20,
    marks: 80,
    date: "2026-06-26",
    status: "Upcoming",
  },
  {
    id: 5,
    title: "IOQM Full-Length Mock Test - 02",
    exam: "IOQM",
    topic: "Full Syllabus",
    testType: "Full Test Series",
    accessType: "Pro",
    externalUrl: "https://quizizz.com/mbc-ioqm-full-02",
    platform: "Quizizz",
    duration: "3 hours",
    questions: 30,
    marks: 100,
    date: "2026-07-02",
    status: "Draft",
  },
  {
    id: 6,
    title: "SEHSS Number Theory Review",
    exam: "SEHSS",
    topic: "Number Theory",
    testType: "Diagnostic",
    accessType: "Pro",
    externalUrl: "https://typeform.com/mbc-sehss-number-review",
    platform: "Typeform",
    duration: "60 min",
    questions: 35,
    marks: 70,
    date: "2026-06-08",
    status: "Completed",
  },
];

export const manageMockTestsAdminNotes = [
  "Tests are hosted externally for the MVP.",
  "Full Test Series access should stay Pro-only.",
  "Free users are redirected to Pro Plans before paid test attempts.",
  "A future version may replace external links with a custom test engine.",
];
